spring.application.name=GATEWAY-Service

security.jwt.enabled=true
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=saludo
spring.cloud.gateway.routes[0].uri=lb://SALUDO-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/saludo/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[1].id=config
spring.cloud.gateway.routes[1].uri=lb://REST-CONFIG
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[2].id=auth
spring.cloud.gateway.routes[2].uri=lb://REST-SECURITY
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter