spring.application.name=GATEWAY-Service

security.jwt.enabled=true
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka



# REST-SALUDO


spring.cloud.gateway.routes[0].id=saludo
spring.cloud.gateway.routes[0].uri=lb://SALUDO-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/saludo/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter



# REST-CONFIG


spring.cloud.gateway.routes[1].id=config
spring.cloud.gateway.routes[1].uri=lb://REST-CONFIG
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/empresas/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[8].id=config
spring.cloud.gateway.routes[8].uri=lb://REST-CONFIG
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/sucursales/**
spring.cloud.gateway.routes[8].filters[0]=AuthenticationFilter



# REST-SECURITY


spring.cloud.gateway.routes[2].id=auth
spring.cloud.gateway.routes[2].uri=lb://REST-SECURITY
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[16].id=auth
spring.cloud.gateway.routes[16].uri=lb://REST-SECURITY
spring.cloud.gateway.routes[16].predicates[0]=Path=/api/rol/**
spring.cloud.gateway.routes[16].filters[0]=AuthenticationFilter


# REST-INVENTARIO


spring.cloud.gateway.routes[3].id=invent
spring.cloud.gateway.routes[3].uri=lb://REST-INVENTARIO
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/productos/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[9].id=invent
spring.cloud.gateway.routes[9].uri=lb://REST-INVENTARIO
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/almacenes/**
spring.cloud.gateway.routes[9].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[10].id=invent
spring.cloud.gateway.routes[10].uri=lb://REST-INVENTARIO
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/categorias/**
spring.cloud.gateway.routes[10].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[11].id=invent
spring.cloud.gateway.routes[11].uri=lb://REST-INVENTARIO
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/stocks/**
spring.cloud.gateway.routes[11].filters[0]=AuthenticationFilter



# REST-CAJA


spring.cloud.gateway.routes[4].id=caja
spring.cloud.gateway.routes[4].uri=lb://REST-CAJA
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/caja/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[5].id=apertura
spring.cloud.gateway.routes[5].uri=lb://REST-CAJA
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/aperturaCaja/**
spring.cloud.gateway.routes[5].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[6].id=cierre
spring.cloud.gateway.routes[6].uri=lb://REST-CAJA
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/cierreCaja/**
spring.cloud.gateway.routes[6].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[7].id=movimiento
spring.cloud.gateway.routes[7].uri=lb://REST-CAJA
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/movimientoCaja/**
spring.cloud.gateway.routes[7].filters[0]=AuthenticationFilter



# REST-PROVEEDOR


spring.cloud.gateway.routes[12].id=proveedor
spring.cloud.gateway.routes[12].uri=lb://REST-PROVEEDOR
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/detalle_compra/**
spring.cloud.gateway.routes[12].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[13].id=proveedor
spring.cloud.gateway.routes[13].uri=lb://REST-PROVEEDOR
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/orden_compra/**
spring.cloud.gateway.routes[13].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[14].id=proveedor
spring.cloud.gateway.routes[14].uri=lb://REST-PROVEEDOR
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/proveedores/**
spring.cloud.gateway.routes[14].filters[0]=AuthenticationFilter



# REST-REPORTE


spring.cloud.gateway.routes[15].id=reporte
spring.cloud.gateway.routes[15].uri=lb://REST-REPORTE
spring.cloud.gateway.routes[15].predicates[0]=Path=/api/reporte/**
spring.cloud.gateway.routes[15].filters[0]=AuthenticationFilter


# REST-VENTA


spring.cloud.gateway.routes[17].id=venta
spring.cloud.gateway.routes[17].uri=lb://REST-VENTA
spring.cloud.gateway.routes[17].predicates[0]=Path=/api/clientes/**
spring.cloud.gateway.routes[17].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[18].id=venta
spring.cloud.gateway.routes[18].uri=lb://REST-VENTA
spring.cloud.gateway.routes[18].predicates[0]=Path=/api/detalleVenta/**
spring.cloud.gateway.routes[18].filters[0]=AuthenticationFilter


spring.cloud.gateway.routes[19].id=venta
spring.cloud.gateway.routes[19].uri=lb://REST-VENTA
spring.cloud.gateway.routes[19].predicates[0]=Path=/api/ventas/**
spring.cloud.gateway.routes[19].filters[0]=AuthenticationFilter